### ISSUE TITLE
Bad Request (400) when opening PayPal Payment Popup (eg clicking Pay with PayPal during checkout)

### ISSUE THREAD

**Issue by MFRWDesign** [solidusio-contrib/solidus_paypal_commerce_platform#103]
After successfully testing the installation locally, we are getting a new error on staging on Heroku.

Our set up:
- We're configuring the app using an initializer, aka:
```ruby
Spree::Config.configure do |config|
  config.static_model_preferences.add(
    SolidusPaypalCommercePlatform::PaymentMethod,
    'paypal_commerce_platform_credentials', {
      test_mode: !Rails.env.production?,
      client_id: ENV['PAYPAL_CLIENT_ID'],
      client_secret: ENV['PAYPAL_CLIENT_SECRET'],
      display_on_product_page: true,
      display_on_cart: true
    }
  )
end
```
- The credentials we're using are from a business account created just for this app, loaded via env variables. More specifically, we are setting `PAYPAL_CLIENT_ID` and `PAYPAL_CLIENT_SECRET`, as well as defining `PAYPAL_ENV=sandbox`.
- We of course also set up the new payment method in the admin using paypal_commerce_platform_credentials as Preference Source.

**Error Report:**
At the payment step, the PayPal buttons show up as expected, but when clicking to use them a 'blank' pop up shows up (never loading the PayPal payment dialog).

**Error message from the console:**
`GET https://staging-server-on-heroku.com/solidus_paypal_commerce_platform/paypal_orders/R684159333?payment_method_id=3&order_token=gtZcM_4Ksdb4aGFZjCah7Q 400 (Bad Request)`

(We have tried using Live credentials and removing the env PAYPAL_ENV=sandbox and the error persists.)

@seand7565 suggested we also add the logs from the server, though as it turns out, they don't provide much info here.
```
2020-10-08T16:23:53.830581+00:00 heroku[router]: at=info method=GET path="/checkout/payment" host=staging-server-on-heroku.com request_id=fa66b7ee-5c5d-4374-9075-3ac875b9ce90 fwd="201.103.30.78" dyno=web.1 connect=1ms service=481ms status=200 bytes=45582 protocol=https
2020-10-08T16:24:02.607026+00:00 heroku[router]: at=info method=GET path="/solidus_paypal_commerce_platform/paypal_orders/R684159333?payment_method_id=3&order_token=gtZcM_4Ksdb4aGFZjCah7Q" host=staging-server-on-heroku.com request_id=19e29e53-9b25-4ca5-af13-12b88df29323 fwd="201.103.30.78" dyno=web.1 connect=1ms service=4ms status=400 bytes=268 protocol=https
2020-10-08T16:24:02.594794+00:00 app[web.1]: I, [2020-10-08T16:24:02.594677 #60]  INFO -- : [19e29e53-9b25-4ca5-af13-12b88df29323] Started GET "/solidus_paypal_commerce_platform/paypal_orders/R684159333?payment_method_id=3&order_token=gtZcM_4Ksdb4aGFZjCah7Q" for 201.103.30.78 at 2020-10-08 16:24:02 +0000
```

Any help is appreciated. From our research so far, it appears this could be coming from sending bad or incomplete order data to PayPal. We will keep digging into it.

**Comment by seand7565** [comment]
Hey Thomas! Some initial thoughts here:
As you mentioned, this is probably the result of ill-formatted data somewhere. Initially, I thought this could be an issue with the data being sent (which is formatted [here](https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/blob/master/app/models/solidus_paypal_commerce_platform/paypal_order.rb)) - because PayPal is very picky that all numbers add up - but in that case, the PayPal dialogue should quit, a JS alert should pop up for the customer, and an error message should be logged to the server log.
<img width="1895" alt="Screen Shot 2020-10-14 at 3 49 14 PM" src="https://user-images.githubusercontent.com/5720486/96043596-d33cd680-0e34-11eb-9283-fab849739f19.png">

But in this case, that doesn't appear to be the case. [This is the request that it should be performing](https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/blob/fa5d9fa923cbd9709a7b7a02ee08f8b933f0e394/app/models/solidus_paypal_commerce_platform/gateway.rb#L75), but seems like something is breaking before then. My guess is it'll be something with the `paypal_order` not building correctly. I'm not sure how customized your installation is, is there any reason you can think of that would make the `paypal_order` not build correctly?

**Comment by MFRWDesign** [comment]
Looks like we finally figured this one out, or more or less. Since the bug only happens when BASIC AUTH is enabled, which we have enabled for our staging server, it seems pretty clear that's the cause. Turning it off produced another error, but as it turned out, that was related to our test credentials.

Once we had Basic AUTH off and switched in the live credentials. It worked just fine. For now, maybe we should just add a note about it in the README since everyone's setup is likely to be a bit different.

Beyond that, I think we might be able to fix this by conditionally adding the Basic Auth credentials directly to the request URL (if the BASIC_AUTH env was set). eg something simple like:
`https://#{ENV['BASIC_AUTH'].present? ? ENV['BASIC_AUTH'] + "@" : ""}staging-server-on-heroku.com/solidus_paypal_commerce_platform/paypal_orders/R684159333?payment_method_id=3&order_token=gtZcM_4Ksdb4aGFZjCah7Q`
