### ISSUE TITLE
Simulated Address Info in Live Order

### ISSUE THREAD

**Issue by MFRWDesign** [solidusio-contrib/solidus_paypal_commerce_platform#104]
After successfully completing a live order in our staging environment, we observed an incorrect Shipping Address in the confirmation email that was sent from PayPal. The address was incorrectly using info from simulated_address for Name and Street Address, instead of using the real information that we had entered as part of our order.

https://monosnap.com/file/6f8t6lmOwjoPMKF2EekmstRUsX99FN

**Comment by seand7565** [comment]
Hey Thomas, thanks for this report! PayPal frustratingly returns a _partial_ address when the user logs in and expects us to recalculate shipping off of that, so that's where the "fake street" comes in - it definitely shouldn't be getting returned _back_ to PayPal and stored as the users actual address though. Looking into it now!

**Comment by MFRWDesign** [comment]
Thanks a lot @seand7565 -- Looking forward to trying this. Might just wait for the merge if you expect it soon.

**Comment by seand7565** [comment]
@MFRWDesign It's been merged! That should fix this issue, though I'll let you try it out and double check before closing this issue. 😄

**Comment by seand7565** [comment]
@MFRWDesign I can't remember if you told me this issue was fixed or not, but I'll close it for now - let me know if you still experience this issue. Thanks!
